### ISSUE TITLE
经常出现下面错误后，后面就必须重启才能使用。没有兜底这个问题么

### ISSUE THREAD

**Issue by lxz2014** [zhile-io/pandora#362]
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/pandora/openai/api.py", line 76, in _do_request_sse
    async with client.stream('POST', url, json=data, headers=headers, timeout=600) as resp:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1576, in stream
    response = await self.send(
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpcore/_async/http_proxy.py", line 289, in handle_async_request
    stream = await stream.start_tls(**kwargs)
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpcore/backends/asyncio.py", line 78, in start_tls
    raise exc
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/httpcore/backends/asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/anyio/streams/tls.py", line 125, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/Users/lixiansheng/Library/Python/3.9/lib/python/site-packages/anyio/streams/tls.py", line 165, in _call_sslobject_method
    raise EndOfStream from None
anyio.EndOfStream

**Comment by jzksnsjswkw** [comment]
找GPT写个shell脚本就行
`
root@localhost:~# cat run.sh
#!/bin/bash

LOG_FILE="GPT.log"
KEYWORD="error"

echo ${PWD}
cd $(dirname "$0")
echo ${PWD}
source /.venv/bin/activate
nohup pandora -t token.txt -s 0.0.0.0:8848 > "$LOG_FILE" 2>&1 &
PID=$!
echo "Service started. PID: $PID"

terminate() {
    if [ -n "$PID" ] && kill -0 "$PID" >/dev/null 2>&1; then
        kill "$PID"
        wait "$PID"
    fi
    exit 0
}

trap terminate INT TERM

while true; do
    if grep -qi "$KEYWORD" "$LOG_FILE"; then
        if [ -n "$PID" ] && kill -0 "$PID" >/dev/null 2>&1; then
            kill "$PID"
            wait "$PID"
        fi
        nohup pandora -t token.txt -s 0.0.0.0:8848 > "$LOG_FILE" 2>&1 &
        PID=$!
        echo "Service restarted. PID: $PID"
    fi
    sleep 3
done
`

**Comment by jzksnsjswkw** [comment]
root@localhost:~# cat run.sh
```shell
#!/bin/bash

LOG_FILE="GPT.log"
KEYWORD="error"

echo ${PWD}
cd $(dirname "$0")
echo ${PWD}
source /.venv/bin/activate
nohup pandora -t token.txt -s 0.0.0.0:8848 > "$LOG_FILE" 2>&1 &
PID=$!
echo "Service started. PID: $PID"

terminate() {
    if [ -n "$PID" ] && kill -0 "$PID" >/dev/null 2>&1; then
        kill "$PID"
        wait "$PID"
    fi
    exit 0
}

trap terminate INT TERM

while true; do
    if grep -qi "$KEYWORD" "$LOG_FILE"; then
        if [ -n "$PID" ] && kill -0 "$PID" >/dev/null 2>&1; then
            kill "$PID"
            wait "$PID"
        fi
        nohup pandora -t token.txt -s 0.0.0.0:8848 > "$LOG_FILE" 2>&1 &
        PID=$!
        echo "Service restarted. PID: $PID"
    fi
    sleep 3
done```
